/*
 * モンスター定義 (章横断)。数値の初期バランスは
 * docs/kazu-quest-design-plan.md A7 に準拠。
 */

import type { MonsterDef } from "./types";

export const MONSTERS: Record<string, MonsterDef> = {
  keshigomun: {
    id: "keshigomun",
    name: "ケシゴムン",
    art: "keshigomun",
    hp: 8,
    atk: 5,
    def: 1,
    agi: 2,
    exp: 2,
    gold: 1,
    actions: [{ kind: "attack", weight: 1 }],
  },
  inkugumo: {
    id: "inkugumo",
    name: "インクぐも",
    art: "inkugumo",
    hp: 12,
    atk: 6,
    def: 2,
    agi: 3,
    exp: 3,
    gold: 2,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 1 },
    ],
  },
  kazunezumi: {
    id: "kazunezumi",
    name: "かずぬすみネズミ",
    art: "kazunezumi",
    hp: 10,
    atk: 6,
    def: 1,
    agi: 6,
    exp: 3,
    gold: 3,
    actions: [{ kind: "attack", weight: 1 }],
  },
  mojibakeBat: {
    id: "mojibakeBat",
    name: "モジバケバット",
    art: "mojibakeBat",
    hp: 14,
    atk: 7,
    def: 2,
    agi: 8,
    exp: 4,
    gold: 3,
    actions: [{ kind: "attack", weight: 1 }],
  },
  togeImomushi: {
    id: "togeImomushi",
    name: "とげとげイモムシ",
    art: "togeImomushi",
    hp: 18,
    atk: 8,
    def: 3,
    agi: 2,
    exp: 5,
    gold: 4,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 1 },
    ],
  },
  dekaInkugumo: {
    id: "dekaInkugumo",
    name: "でかインクぐも",
    art: "dekaInkugumo",
    hp: 60,
    atk: 10,
    def: 3,
    agi: 4,
    exp: 20,
    gold: 30,
    actions: [
      { kind: "attack", weight: 2 },
      { kind: "strongAttack", weight: 1 },
    ],
  },
  /* ---------- 第2章 (海辺と九九の塔) ---------- */
  awaKeshigomun: {
    id: "awaKeshigomun",
    name: "あわケシゴムン",
    art: "awaKeshigomun",
    hp: 16,
    atk: 9,
    def: 3,
    agi: 5,
    exp: 7,
    gold: 5,
    actions: [{ kind: "attack", weight: 1 }],
  },
  inkgani: {
    id: "inkgani",
    name: "インクガニ",
    art: "inkgani",
    hp: 20,
    atk: 10,
    def: 6,
    agi: 3,
    exp: 9,
    gold: 7,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 1 },
    ],
  },
  shuseiekin: {
    id: "shuseiekin",
    name: "シュウセイエキン",
    art: "shuseiekin",
    hp: 24,
    atk: 11,
    def: 4,
    agi: 7,
    exp: 11,
    gold: 9,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "heal", weight: 1 },
    ],
  },
  blotta: {
    id: "blotta",
    name: "インクの魔女ブロッタ",
    art: "blotta",
    hp: 160,
    atk: 15,
    def: 6,
    agi: 8,
    exp: 180,
    gold: 350,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 2 },
      { kind: "heal", weight: 1 },
    ],
  },
  /* ---------- 第3章 (砂の国ワケーラ) ---------- */
  sunaKeshigomun: {
    id: "sunaKeshigomun",
    name: "すなケシゴムン",
    art: "sunaKeshigomun",
    hp: 28,
    atk: 14,
    def: 5,
    agi: 6,
    exp: 16,
    gold: 12,
    actions: [{ kind: "attack", weight: 1 }],
  },
  sunanezumi: {
    id: "sunanezumi",
    name: "すなぬすみネズミ",
    art: "sunanezumi",
    hp: 26,
    atk: 13,
    def: 4,
    agi: 12,
    exp: 15,
    gold: 18,
    actions: [{ kind: "attack", weight: 1 }],
  },
  cactusKnife: {
    id: "cactusKnife",
    name: "サボテンナイフ",
    art: "cactusKnife",
    hp: 34,
    atk: 16,
    def: 8,
    agi: 5,
    exp: 20,
    gold: 15,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 2 },
    ],
  },
  sasoriCompass: {
    id: "sasoriCompass",
    name: "さそりコンパス",
    art: "sasoriCompass",
    hp: 30,
    atk: 18,
    def: 6,
    agi: 10,
    exp: 22,
    gold: 16,
    actions: [
      { kind: "attack", weight: 2 },
      { kind: "strongAttack", weight: 1 },
    ],
  },
  mummyFusen: {
    id: "mummyFusen",
    name: "ミイラふせん",
    art: "mummyFusen",
    hp: 40,
    atk: 17,
    def: 9,
    agi: 4,
    exp: 26,
    gold: 20,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "heal", weight: 1 },
    ],
  },
  wakemaeGolem: {
    id: "wakemaeGolem",
    name: "わけまえゴーレム",
    art: "wakemaeGolem",
    hp: 110,
    atk: 20,
    def: 12,
    agi: 3,
    exp: 90,
    gold: 90,
    actions: [
      { kind: "attack", weight: 2 },
      { kind: "strongAttack", weight: 1 },
    ],
  },
  amarida: {
    id: "amarida",
    name: "盗賊王アマリダ",
    art: "amarida",
    hp: 260,
    atk: 24,
    def: 10,
    agi: 14,
    exp: 400,
    gold: 700,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 2 },
      { kind: "heal", weight: 1 },
    ],
  },
  eraser: {
    id: "eraser",
    name: "幹部イレイサー",
    art: "eraser",
    hp: 90,
    atk: 12,
    def: 4,
    agi: 5,
    exp: 60,
    gold: 100,
    actions: [
      { kind: "attack", weight: 3 },
      { kind: "strongAttack", weight: 2 },
      { kind: "heal", weight: 1 },
    ],
  },
};

export function getMonster(id: string): MonsterDef | undefined {
  return MONSTERS[id];
}
